"""
Snowflake Day-0 Platform Setup
=================================
A Streamlit-in-Snowflake application that generates and deploys a complete
Snowflake data platform from a guided 4-step wizard:

  Step 1 — Project Setup: naming, environments, domains, storage, tables,
           file formats, stages, ingestion, retention.
  Step 2 — Environment Config: per-env warehouse sizing, scaling, timeouts,
           resource monitors, optional ETL warehouse separation.
  Step 3 — Security & Governance: roles, masking, row access, projection,
           network policies, tagging, classification, cost management.
  Step 4 — Review & Deploy: AI-generated DDL via Cortex Complete, script
           review, one-click deployment, post-deploy validation.

Architecture Notes:
  - All DDL is generated by an LLM (Cortex Complete) using a structured
    prompt built from the user's config.  The prompt explicitly specifies
    Snowflake object names, parameters, and execution order.
  - Deployment executes statements sequentially with per-statement error
    handling and rollback logging.
  - Validation queries confirm every expected object exists after deploy.

Usage:
  Run as a Streamlit-in-Snowflake app from Snowsight.
"""

import streamlit as st
import json
import time
from datetime import datetime
from snowflake.snowpark.context import get_active_session

# ---------------------------------------------------------------------------
# Snowpark session — authenticated via Snowsight hosting context
# ---------------------------------------------------------------------------
session = get_active_session()

# ---------------------------------------------------------------------------
# Supported Cortex LLM models for SQL generation
# ---------------------------------------------------------------------------
MODELS = ["mistral-large2", "llama3.1-70b", "llama3.1-405b", "llama3.3-70b", "claude-3-5-sonnet", "snowflake-arctic"]

# ---------------------------------------------------------------------------
# Contextual help text — displayed as (?) tooltips beside each input widget
# ---------------------------------------------------------------------------
TOOLTIP = {
    "project_name": "A unique identifier for your Snowflake project. Use UPPER_SNAKE_CASE (e.g., SALES_ANALYTICS). This becomes the prefix for all databases, warehouses, and roles created.",
    "business_unit": "The department or team owning this project (e.g., Finance, Marketing). Used for cost allocation tags and access grouping.",
    "environments": "Select the deployment stages your data platform requires. DEV for development, QA for testing, STAGING for pre-production validation, PROD for live workloads. Each environment gets its own database, warehouse, and role hierarchy.",
    "naming_convention": "Defines how Snowflake objects are named. <PROJECT>_<ENV>_<OBJECT> groups by project first (recommended for multi-project orgs). <ENV>_<PROJECT>_<OBJECT> groups by environment first (useful for env-level governance).",
    "data_domains": "Logical layers in your data architecture. RAW = landed data as-is. STAGING = cleaned/typed. CLEANSED = validated/deduped. CURATED = business-ready. ANALYTICS = aggregated for BI. DATA_SCIENCE = ML features. SANDBOX = ad-hoc exploration. ARCHIVE = historical/cold storage.",
    "ingestion_types": "How data enters Snowflake. Batch (COPY INTO) = scheduled bulk loads. Snowpipe = near-real-time auto-ingest from stage. Streams & Tasks = CDC-based incremental processing. External Tables = query data in-place on cloud storage. Data Sharing = cross-account data access.",
    "warehouse_size": "Compute power for the warehouse. XSMALL (1 credit/hr) for light queries. SMALL (2) for dashboards. MEDIUM (4) for ETL. LARGE (8) for heavy transforms. XLARGE (16) for complex analytics. 2XLARGE (32) for massive workloads.",
    "auto_suspend": "Seconds of inactivity before the warehouse auto-suspends to stop billing. 60s for interactive/dev (fast resume). 300s balanced. 600-3600s for batch workloads where resume latency is acceptable.",
    "min_clusters": "Minimum warehouses always running in multi-cluster mode. 1 for most cases. Increase for guaranteed concurrency during peak hours. Higher values = higher base cost.",
    "max_clusters": "Maximum warehouses that can scale out under load. 1 for DEV (cost control). 3-5 for PROD (handle concurrency spikes). Auto-scaling adds clusters when queries queue.",
    "scaling_policy": "STANDARD = adds clusters when queries queue, removes after idle period. ECONOMY = waits longer before adding clusters, favoring cost savings over speed.",
    "query_timeout": "Maximum seconds a query can run before auto-cancellation. Prevents runaway queries from consuming credits. 300s for interactive, 3600s for ETL, 7200s for heavy batch.",
    "resource_monitor": "Credit usage threshold that triggers alerts or suspends the warehouse. Set per-environment to control spend. DEV typically gets lower limits than PROD.",
    "roles": "Functional access roles for your platform. ADMIN = full control. DEVELOPER = create/modify objects. DATA_ENGINEER = ETL pipelines. ANALYST = read analytics. DATA_SCIENTIST = ML workloads. READER = read-only. WRITER = insert/update. SERVICE_ACCOUNT = automated processes.",
    "masking": "Dynamic Data Masking applies column-level security policies that mask sensitive data (SSN, email, PII) at query time based on the user's role. No data duplication needed.",
    "row_access": "Row Access Policies filter rows returned to users based on their role or attributes. E.g., regional managers only see their region's data. Applied transparently at query time.",
    "column_access": "Projection Policies prevent specific columns from appearing in query results for unauthorized roles. Stronger than masking — the column is entirely hidden, not just obfuscated.",
    "tagging": "Object Tagging lets you attach key-value metadata to databases, schemas, tables, and columns. Used for governance, cost tracking, data classification, and lineage.",
    "classification": "Data Classification automatically scans columns to detect sensitive data categories (PII, PHI, financial). Works with Snowflake's built-in classifiers or custom rules.",
    "access_history": "Access History tracks who queried what data and when. Required for compliance audits (GDPR, HIPAA, SOX). Available via SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY view.",
    "cost_tags": "Cost Center Tags attach billing metadata to warehouses and queries. Enables chargeback/showback reporting by team, project, or department.",
    "resource_monitors": "Resource Monitors set credit usage thresholds at account or warehouse level. Configurable actions: NOTIFY (alert), SUSPEND (stop warehouse), SUSPEND_IMMEDIATELY (kill running queries).",
    "credit_quota": "Monthly credit budget for this project across all environments. Triggers resource monitor alerts at 75%/90%/100%. Helps prevent unexpected cost overruns.",
    "data_retention": "Time Travel retention in days. Allows querying/restoring data as it existed up to N days ago. 1 day = standard. 7 days for regulated data. 90 days max for Enterprise edition.",
    "network_policy": "Restrict Snowflake access to specific IP ranges. Critical for production environments. Supports allowlists and blocklists. Applied at account or user level.",
    "db_storage_type": "Database storage type. PERMANENT (default) = full Time Travel (0-90 days) + 7-day Fail-Safe. TRANSIENT = Time Travel 0-1 day only, NO Fail-Safe. Use Transient for DEV/STAGING to reduce storage costs. Permanent for PROD/regulated data.",
    "schema_storage_type": "Override storage type per data domain schema. INHERIT = uses the database setting. TRANSIENT = no Fail-Safe, max 1-day Time Travel (good for RAW/STAGING landing zones). PERMANENT = full Fail-Safe + Time Travel (good for CURATED/ANALYTICS). Mix types to optimize cost vs. recoverability.",
    "initial_tables": "Define seed tables to create during Day-0 setup. Specify table name, target schema (domain), column definitions, and table type. These are scaffolding tables for your data pipeline — actual data loads come later.",
    "table_type": "PERMANENT = full Time Travel + 7-day Fail-Safe (default for important data). TRANSIENT = no Fail-Safe, 0-1 day Time Travel (good for staging/landing tables). TEMPORARY = session-scoped, auto-dropped (not used in Day-0 setup).",
    "table_columns": "Define columns as NAME DATATYPE pairs, one per line. E.g. ID NUMBER, NAME VARCHAR(100), CREATED_AT TIMESTAMP_NTZ. Use Snowflake data types.",
    "file_formats": "Named file formats define how data files are parsed during loading. Create reusable formats for CSV, JSON, or PARQUET to standardize ingestion across your platform.",
    "stages": "Internal stages are named locations in Snowflake where data files are stored before loading. Each environment typically needs its own stage in the RAW schema for data landing.",
}

# ---------------------------------------------------------------------------
# Best-practice tips shown in a card at the bottom of each step
# ---------------------------------------------------------------------------
BEST_PRACTICES = {
    1: [
        "Use consistent UPPER_SNAKE_CASE naming across all objects",
        "Separate environments with distinct databases, not schemas",
        "Include at least DEV and PROD environments",
        "Plan data domains upfront — retrofitting is expensive",
        "Use TRANSIENT databases for DEV/STAGING to save storage costs — no Fail-Safe overhead",
        "Keep PROD databases PERMANENT for full recoverability (Time Travel + Fail-Safe)",
        "Define seed tables with explicit column types — avoid relying on schema-on-read",
        "Create named file formats early — reuse them across stages and COPY INTO statements",
    ],
    2: [
        "Start small (XSMALL/SMALL) and scale up based on metrics",
        "Set auto-suspend to 60s for dev, 300s for prod",
        "Use multi-cluster warehouses in PROD for concurrency",
        "Separate ETL and BI warehouses to avoid resource contention",
        "Enable STATEMENT_TIMEOUT to prevent runaway queries from burning credits",
    ],
    3: [
        "Follow least-privilege principle for all role grants",
        "Enable data classification before going to production",
        "Set up resource monitors BEFORE granting warehouse access",
        "Tag all objects at creation — retroactive tagging is tedious",
        "Use FUTURE GRANTS so new tables/views auto-inherit permissions",
    ],
    4: [
        "Always review generated SQL before deploying",
        "Deploy to DEV first, validate, then promote to PROD",
        "Keep an audit log of all deployments for compliance",
        "Test role grants with a non-admin user after deployment",
    ],
}

# ---------------------------------------------------------------------------
# Page configuration & custom CSS
# ---------------------------------------------------------------------------
st.set_page_config(page_title="Day-0 Platform Setup", layout="wide")
st.markdown("""
<style>
    .main .block-container { padding-top: 1.5rem; max-width: 1200px; }
    .step-indicator {
        background: linear-gradient(135deg, #1B6AC9, #2E8AE6);
        color: white; padding: 4px 14px; border-radius: 20px;
        font-size: 0.75rem; font-weight: 600; letter-spacing: 0.5px;
    }
    .skill-badge {
        background: linear-gradient(135deg, #0D9373, #12B88A);
        color: white; padding: 3px 12px; border-radius: 14px;
        font-size: 0.75rem; font-weight: 600;
    }
    .success-box {
        background: linear-gradient(135deg, #E8F9F0, #D1F5E0);
        border: 1px solid #0D9373; border-radius: 12px;
        padding: 20px; text-align: center;
    }
    .success-box h3 { color: #0D9373; margin: 0; }
    .summary-card {
        background: #FAFBFD; border: 1px solid #E2E8F0;
        border-radius: 10px; padding: 16px; margin-bottom: 12px;
    }
    .summary-card h4 { margin: 0 0 8px 0; color: #1a3a5c; font-size: 0.95rem; }
    .summary-card p { margin: 2px 0; font-size: 0.85rem; color: #4a5568; }
    .exec-step {
        padding: 8px 12px; border-radius: 6px; margin: 4px 0;
        font-size: 0.82rem; font-family: monospace;
    }
    .exec-ok { background: #E8F9F0; border-left: 3px solid #0D9373; }
    .exec-fail { background: #FFF0F0; border-left: 3px solid #E53E3E; }
    .progress-step {
        display: inline-block; padding: 6px 16px; border-radius: 20px;
        font-size: 0.8rem; font-weight: 600; margin: 2px;
    }
    .progress-active { background: #1B6AC9; color: white; }
    .progress-done { background: #0D9373; color: white; }
    .progress-pending { background: #E2E8F0; color: #718096; }
    .bp-card {
        background: #FFFBEB; border: 1px solid #F6E05E;
        border-radius: 8px; padding: 12px; margin-top: 10px;
    }
    .bp-card li { font-size: 0.78rem; color: #744210; margin: 4px 0; }
    div[data-testid="stExpander"] details summary p { font-weight: 600; }
    /* Centered deployment metrics */
    .deploy-metrics {
        display: flex; justify-content: center; gap: 2rem;
        padding: 16px 0; margin: 8px 0;
    }
    .deploy-metric {
        text-align: center; min-width: 100px;
        background: #FAFBFD; border: 1px solid #E2E8F0;
        border-radius: 10px; padding: 12px 20px;
    }
    .deploy-metric .value {
        font-size: 1.6rem; font-weight: 700; color: #1a3a5c;
        line-height: 1.2;
    }
    .deploy-metric .label {
        font-size: 0.72rem; color: #718096; text-transform: uppercase;
        letter-spacing: 0.5px; margin-top: 2px;
    }
    .deploy-metric.ok .value { color: #0D9373; }
    .deploy-metric.fail .value { color: #E53E3E; }
    .deploy-metric.time .value { color: #1B6AC9; }
    /* Reset button styling */
    button[kind="secondary"]:has(> div > p) { transition: all 0.15s; }
    .reset-btn-wrap button {
        background: linear-gradient(135deg, #E53E3E, #C53030) !important;
        color: white !important; border: none !important;
        font-weight: 600 !important;
    }
    .reset-btn-wrap button:hover {
        background: linear-gradient(135deg, #C53030, #9B2C2C) !important;
        box-shadow: 0 2px 8px rgba(229,62,62,0.3) !important;
    }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------------------------
# Session state defaults — initialised once per browser session
# ---------------------------------------------------------------------------
if "step" not in st.session_state:
    st.session_state.step = 1
if "config" not in st.session_state:
    st.session_state.config = {}
if "generated_sql" not in st.session_state:
    st.session_state.generated_sql = None
if "deployment_complete" not in st.session_state:
    st.session_state.deployment_complete = False
if "deployment_result" not in st.session_state:
    st.session_state.deployment_result = None
if "exec_log" not in st.session_state:
    st.session_state.exec_log = []
if "validation_sql" not in st.session_state:
    st.session_state.validation_sql = None
if "review_confirmed" not in st.session_state:
    st.session_state.review_confirmed = False
if "validation_results" not in st.session_state:
    st.session_state.validation_results = []
if "table_counter" not in st.session_state:
    st.session_state.table_counter = 0


# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------

def _dbg(msg):
    """Append a timestamped debug message to the session debug log."""
    ts = datetime.now().strftime("%H:%M:%S.%f")[:-3]
    st.session_state.setdefault("_debug_log", []).append(f"[{ts}] {msg}")


def resolve_name(project, env, suffix, naming):
    """Build a Snowflake object name respecting the chosen naming convention.

    Args:
        project: project prefix   (e.g. "SALES_ANALYTICS")
        env:     environment code (e.g. "DEV")
        suffix:  object suffix    (e.g. "DB", "WH", "MONITOR")
        naming:  naming template  ("<PROJECT>_<ENV>_<OBJECT>" or
                                   "<ENV>_<PROJECT>_<OBJECT>")
    Returns:
        Fully resolved name, e.g. "SALES_ANALYTICS_DEV_DB".
    """
    if naming == "<PROJECT>_<ENV>_<OBJECT>":
        return project + "_" + env + "_" + suffix
    return env + "_" + project + "_" + suffix


def safe_rerun():
    """Wrapper around st.rerun() for forward-compatibility."""
    _dbg("Triggering rerun")
    st.rerun()


def render_progress():
    """Render the horizontal 4-step progress bar at the top of the page."""
    labels = {1: "Project Setup", 2: "Environment Config", 3: "Security & Governance", 4: "Review & Deploy"}
    html = ""
    for sn, sl in labels.items():
        if sn < st.session_state.step:
            html += '<span class="progress-step progress-done">&#10003; ' + sl + '</span>'
        elif sn == st.session_state.step:
            html += '<span class="progress-step progress-active">' + str(sn) + '. ' + sl + '</span>'
        else:
            html += '<span class="progress-step progress-pending">' + str(sn) + '. ' + sl + '</span>'
    st.markdown(html, unsafe_allow_html=True)


def render_best_practices(step):
    """Show a collapsible best-practices card relevant to the current step."""
    bps = BEST_PRACTICES.get(step, [])
    if bps:
        items = "".join("<li>" + b + "</li>" for b in bps)
        st.markdown('<div class="bp-card"><strong>Best Practices</strong><ul>' + items + '</ul></div>', unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Skill registry — loads prompt templates from SKILL_DB.SKILLS.SKILL_REGISTRY
# ---------------------------------------------------------------------------

def load_skills():
    """Fetch active skills (system prompt templates) from the registry table.

    Falls back to a minimal DEFAULT skill if the registry is unreachable.
    """
    _dbg("Loading skills from SKILL_DB.SKILLS.SKILL_REGISTRY")
    try:
        rows = session.sql(
            "SELECT SKILL_NAME, SKILL_DESCRIPTION, SKILL_CONTENT, DEFAULT_MODEL "
            "FROM SKILL_DB.SKILLS.SKILL_REGISTRY "
            "WHERE IS_ACTIVE = TRUE ORDER BY SKILL_NAME"
        ).collect()
        return [{"name": r["SKILL_NAME"], "description": r["SKILL_DESCRIPTION"],
                 "content": r["SKILL_CONTENT"], "model": r["DEFAULT_MODEL"]} for r in rows]
    except Exception as exc:
        _dbg(f"Skill registry unavailable: {exc}")
        return [{"name": "DEFAULT", "description": "Fallback skill",
                 "content": "Generate Snowflake DDL for a data platform.", "model": MODELS[0]}]


def load_templates():
    """Placeholder for future template loading (e.g. industry-specific scaffolds)."""
    return {}


# ---------------------------------------------------------------------------
# Cortex Complete — LLM call wrapper
# ---------------------------------------------------------------------------

def call_cortex_complete(model, system_prompt, user_prompt):
    """Call Snowflake Cortex Complete and return (response_text, usage_dict)."""
    _dbg(f"Calling Cortex Complete with model={model}, prompt_len={len(user_prompt)}")
    from snowflake.snowpark.functions import col, lit, parse_json
    conversation = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
    options = {"temperature": 0.1, "max_tokens": 8000}
    conv_json = json.dumps(conversation)
    opts_json = json.dumps(options)
    result = session.sql(
        "SELECT SNOWFLAKE.CORTEX.COMPLETE(?, PARSE_JSON(?), PARSE_JSON(?)) AS response",
        params=[model, conv_json, opts_json]
    ).collect()
    raw_response = result[0]["RESPONSE"]
    if isinstance(raw_response, str):
        try:
            parsed = json.loads(raw_response)
            text = parsed.get("choices", [{}])[0].get("messages", parsed.get("choices", [{}])[0].get("message", ""))
            if isinstance(text, dict):
                text = text.get("content", "")
            elif isinstance(text, str):
                pass
            else:
                text = str(text)
            usage = parsed.get("usage", {})
        except (json.JSONDecodeError, KeyError, IndexError):
            text = raw_response
            usage = {}
    else:
        text = str(raw_response)
        usage = {}
    return text, usage


# ---------------------------------------------------------------------------
# Validation SQL builder — generates queries to verify deployed objects exist
# ---------------------------------------------------------------------------

def build_validation_sql(config):
    """Build a SQL script of SELECT/SHOW queries that verify every expected
    object (database, schema, warehouse, role, table, file format, stage)
    was successfully created.
    """
    _dbg("Building validation SQL")
    project = config.get("project_name", "PROJECT")
    envs = config.get("environments", ["DEV", "PROD"])
    domains = config.get("data_domains", ["RAW", "STAGING", "ANALYTICS"])
    naming = config.get("naming_convention", "<PROJECT>_<ENV>_<OBJECT>")
    roles = config.get("roles", ["ADMIN", "DEVELOPER", "ANALYST", "READER"])
    gov = config.get("governance", {})
    wh_config = config.get("warehouse_config", {})
    sep_etl = config.get("separate_etl_wh", False)
    stmts = []
    stmts.append("-- ============================================")
    stmts.append("-- VALIDATION QUERIES")
    stmts.append("-- Run these after deployment to verify objects")
    stmts.append("-- ============================================")

    # --- Databases ---
    for env in envs:
        db_name = resolve_name(project, env, "DB", naming)
        stmts.append("SELECT '" + db_name + "' AS EXPECTED_DATABASE, COUNT(*) AS FOUND FROM INFORMATION_SCHEMA.DATABASES WHERE DATABASE_NAME = '" + db_name + "';")
    # --- Schemas ---
    for env in envs:
        db_name = resolve_name(project, env, "DB", naming)
        for dom in domains:
            stmts.append("SELECT '" + db_name + "." + dom + "' AS EXPECTED_SCHEMA, COUNT(*) AS FOUND FROM " + db_name + ".INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '" + dom + "';")

    # --- Warehouses ---
    for env in envs:
        wh_name = resolve_name(project, env, "WH", naming)
        stmts.append("SHOW WAREHOUSES LIKE '" + wh_name + "';")
        if sep_etl:
            etl_name = wh_name.replace("_WH", "_ETL_WH")
            stmts.append("SHOW WAREHOUSES LIKE '" + etl_name + "';")

    # --- Roles ---
    for role in roles:
        full_role = project + "_" + role
        stmts.append("SHOW ROLES LIKE '" + full_role + "';")

    # --- Resource Monitors ---
    if gov.get("resource_monitors", True):
        stmts.append("SHOW RESOURCE MONITORS LIKE '" + project + "%';")

    # --- Masking Policies ---
    if gov.get("masking", True):
        for env in envs:
            db_name = resolve_name(project, env, "DB", naming)
            stmts.append("SHOW MASKING POLICIES IN " + db_name + ";")
            break

    # --- Tags ---
    if gov.get("tagging", True):
        for env in envs:
            db_name = resolve_name(project, env, "DB", naming)
            stmts.append("SHOW TAGS IN " + db_name + ";")
            break
    # --- Tables ---
    initial_tables = config.get("initial_tables", [])
    valid_tables = [t for t in initial_tables if t.get("name")]
    for t in valid_tables:
        for env in envs:
            db_name = resolve_name(project, env, "DB", naming)
            fqn = db_name + "." + t["domain"] + "." + t["name"]
            stmts.append("SELECT '" + fqn + "' AS EXPECTED_TABLE, COUNT(*) AS FOUND FROM " + db_name + ".INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '" + t["domain"] + "' AND TABLE_NAME = '" + t["name"] + "';")

    # --- File Formats ---
    file_formats = config.get("file_formats", [])
    valid_formats = [f for f in file_formats if f.get("name")]
    if valid_formats:
        first_env = envs[0] if envs else "DEV"
        ff_db = resolve_name(project, first_env, "DB", naming)
        for f in valid_formats:
            f_schema = f.get("schema", "RAW" if "RAW" in domains else domains[0])
            stmts.append("SELECT '" + ff_db + "." + f_schema + "." + f["name"] + "' AS EXPECTED_FORMAT, COUNT(*) AS FOUND FROM " + ff_db + ".INFORMATION_SCHEMA.FILE_FORMATS WHERE FILE_FORMAT_NAME = '" + f["name"] + "';")

    # --- Stages ---
    stages_cfg = config.get("stages", [])
    valid_stages = [s for s in stages_cfg if s.get("name")]
    for s in valid_stages:
        for env in envs:
            db_name = resolve_name(project, env, "DB", naming)
            s_schema = s.get("schema", "RAW" if "RAW" in domains else domains[0])
            stmts.append("SHOW STAGES LIKE '" + s["name"] + "' IN " + db_name + "." + s_schema + ";")

    _dbg(f"Validation SQL: {len(stmts)} statements")
    return "\n".join(stmts)


# ---------------------------------------------------------------------------
# Post-deploy object validation
# ---------------------------------------------------------------------------

def run_validation(validation_sql):
    """Execute each validation statement and return a list of result dicts
    with keys: object, status (FOUND/MISSING/ERROR), detail.
    """
    _dbg("Running validation queries")
    stmts = [s.strip() for s in validation_sql.split(";") if s.strip() and not s.strip().startswith("--")]
    results = []
    for stmt in stmts:
        try:
            rows = session.sql(stmt).collect()
            row_count = len(rows)
            if stmt.strip().upper().startswith("SELECT"):
                found_val = rows[0][1] if rows and len(rows[0]) > 1 else 0
                obj_name = rows[0][0] if rows else stmt[:60]
                results.append({"object": str(obj_name), "status": "FOUND" if int(found_val) > 0 else "MISSING", "detail": str(found_val) + " match(es)"})
            elif stmt.strip().upper().startswith("SHOW"):
                obj_desc = stmt.replace("SHOW ", "").replace(";", "")[:60]
                results.append({"object": obj_desc, "status": "FOUND" if row_count > 0 else "MISSING", "detail": str(row_count) + " result(s)"})
        except Exception as e:
            results.append({"object": stmt[:60], "status": "ERROR", "detail": str(e)[:200]})
    return results


# ---------------------------------------------------------------------------
# LLM prompt builder — assembles a structured prompt from the user's config
# that instructs the LLM to produce Snowflake DDL in the correct execution
# order:  USE ROLE → databases → schemas → tables → file formats → stages →
# warehouses → roles/grants → policies → monitors → tags.
# ---------------------------------------------------------------------------

def build_user_prompt(config):
    """Convert the wizard config dict into a detailed natural-language prompt
    for Cortex Complete to generate executable Snowflake DDL.
    """
    _dbg("Building user prompt from config")
    project = config.get("project_name", "PROJECT")
    envs = config.get("environments", ["DEV", "PROD"])
    domains = config.get("data_domains", ["RAW", "STAGING", "ANALYTICS"])
    naming = config.get("naming_convention", "<PROJECT>_<ENV>_<OBJECT>")
    wh_config = config.get("warehouse_config", {})
    roles = config.get("roles", ["ADMIN", "DEVELOPER", "ANALYST", "READER"])
    gov = config.get("governance", {})
    tt_days = config.get("time_travel_days", 1)
    ingestion = config.get("ingestion_types", [])
    cost_mgmt = config.get("cost_management", {})
    sep_etl = config.get("separate_etl_wh", False)
    owner = config.get("project_owner", "")
    bu = config.get("business_unit", "")
    db_storage_type = config.get("db_storage_type", "PERMANENT")
    schema_overrides = config.get("schema_storage_overrides", {})
    initial_tables = config.get("initial_tables", [])
    file_formats = config.get("file_formats", [])
    stages = config.get("stages", [])

    prompt_parts = []
    prompt_parts.append("Generate complete Snowflake SQL DDL for a data platform. Output ONLY valid SQL statements separated by semicolons. No markdown fences, no commentary, no explanations.")
    prompt_parts.append("")
    prompt_parts.append("=== PROJECT ===")
    prompt_parts.append("Name: " + project)
    prompt_parts.append("Owner: " + owner)
    prompt_parts.append("Business Unit: " + bu)
    prompt_parts.append("Naming Convention: " + naming)
    prompt_parts.append("Environments: " + ", ".join(envs))
    prompt_parts.append("Data Domains (schemas per env DB): " + ", ".join(domains))
    prompt_parts.append("Time Travel Days: " + str(tt_days))
    prompt_parts.append("Ingestion Methods: " + ", ".join(ingestion))
    prompt_parts.append("")

    # --- Databases & Schemas ---
    prompt_parts.append("=== DATABASES & SCHEMAS ===")
    prompt_parts.append("For EACH environment, create one database with all domain schemas.")
    if db_storage_type == "TRANSIENT":
        prompt_parts.append("All databases MUST be created as TRANSIENT (use CREATE TRANSIENT DATABASE IF NOT EXISTS).")
        prompt_parts.append("TRANSIENT databases: no Fail-Safe, Time Travel limited to 0-1 day.")
    else:
        prompt_parts.append("All databases should be PERMANENT (default CREATE DATABASE IF NOT EXISTS).")
    for env in envs:
        db_name = resolve_name(project, env, "DB", naming)
        prompt_parts.append("- Database: " + db_name + " with schemas: " + ", ".join(domains))
    has_overrides = any(v != "INHERIT" for v in schema_overrides.values())
    if has_overrides:
        prompt_parts.append("Schema storage type overrides (override the database default):")
        for dom, stype in schema_overrides.items():
            if stype == "TRANSIENT":
                prompt_parts.append("- Schema " + dom + ": CREATE TRANSIENT SCHEMA IF NOT EXISTS (no Fail-Safe, max 1-day Time Travel)")
            elif stype == "PERMANENT" and db_storage_type == "TRANSIENT":
                prompt_parts.append("- Schema " + dom + ": CREATE SCHEMA IF NOT EXISTS (permanent, override transient DB default)")
    prompt_parts.append("Set DATA_RETENTION_TIME_IN_DAYS = " + str(tt_days) + " on each database.")
    if db_storage_type == "TRANSIENT":
        prompt_parts.append("IMPORTANT: For TRANSIENT databases/schemas, DATA_RETENTION_TIME_IN_DAYS must be 0 or 1 only.")
    prompt_parts.append("Use CREATE DATABASE IF NOT EXISTS and CREATE SCHEMA IF NOT EXISTS (with TRANSIENT keyword where specified above).")
    prompt_parts.append("")

    # --- Warehouses ---
    prompt_parts.append("=== WAREHOUSES ===")
    for env in envs:
        wc = wh_config.get(env, {})
        wh_name = resolve_name(project, env, "WH", naming)
        prompt_parts.append("- Warehouse: " + wh_name)
        prompt_parts.append("  SIZE = '" + wc.get("size", "SMALL") + "'")
        prompt_parts.append("  AUTO_SUSPEND = " + str(wc.get("auto_suspend", 300)))
        prompt_parts.append("  AUTO_RESUME = TRUE")
        prompt_parts.append("  MIN_CLUSTER_COUNT = " + str(wc.get("min_clusters", 1)))
        prompt_parts.append("  MAX_CLUSTER_COUNT = " + str(wc.get("max_clusters", 1)))
        prompt_parts.append("  SCALING_POLICY = '" + wc.get("scaling_policy", "STANDARD") + "'")
        prompt_parts.append("  STATEMENT_TIMEOUT_IN_SECONDS = " + str(wc.get("query_timeout", 3600)))
        if sep_etl:
            etl_name = wh_name.replace("_WH", "_ETL_WH")
            prompt_parts.append("- Also create ETL warehouse: " + etl_name + " with same settings")
    prompt_parts.append("Use CREATE WAREHOUSE IF NOT EXISTS.")
    prompt_parts.append("")

    # --- Roles & Grants ---
    prompt_parts.append("=== ROLES & GRANTS ===")
    prompt_parts.append("Create these functional roles (prefix with " + project + "_):")
    for role in roles:
        prompt_parts.append("- " + project + "_" + role)
    prompt_parts.append("Create a role hierarchy: ADMIN at top, grant all other roles to ADMIN.")
    prompt_parts.append("Grant appropriate privileges:")
    prompt_parts.append("- ADMIN: USAGE + ALL on all databases, schemas, warehouses")
    prompt_parts.append("- DEVELOPER: USAGE on databases/schemas, CREATE TABLE/VIEW/PROCEDURE/FUNCTION, USAGE on warehouses")
    prompt_parts.append("- DATA_ENGINEER: Same as DEVELOPER plus CREATE STAGE, CREATE PIPE, CREATE STREAM, CREATE TASK")
    prompt_parts.append("- ANALYST: USAGE on databases/schemas, SELECT on all tables/views, USAGE on warehouses")
    prompt_parts.append("- DATA_SCIENTIST: Same as ANALYST plus CREATE TABLE in SANDBOX/DATA_SCIENCE schemas")
    prompt_parts.append("- READER: USAGE on databases/schemas, SELECT on ANALYTICS/CURATED schemas")
    prompt_parts.append("- WRITER: Same as READER plus INSERT, UPDATE on applicable schemas")
    prompt_parts.append("- SERVICE_ACCOUNT: Specific grants for automated ETL processes")
    prompt_parts.append("Grant " + project + "_ADMIN to SYSADMIN.")
    prompt_parts.append("Use CREATE ROLE IF NOT EXISTS.")
    prompt_parts.append("IMPORTANT: Add GRANT ON FUTURE TABLES/VIEWS in each schema to the appropriate roles so new objects auto-inherit permissions.")
    prompt_parts.append("")

    # --- Resource Monitors ---
    if gov.get("resource_monitors", True):
        prompt_parts.append("=== RESOURCE MONITORS ===")
        thresholds = gov.get("alert_thresholds", [75, 90, 100])
        for env in envs:
            wc = wh_config.get(env, {})
            credits = wc.get("resource_monitor_credits", 100)
            mon_name = resolve_name(project, env, "MONITOR", naming)
            wh_name = resolve_name(project, env, "WH", naming)
            prompt_parts.append("- Monitor: " + mon_name + " CREDIT_QUOTA = " + str(credits) + " FREQUENCY = MONTHLY")
            for t in thresholds:
                action = "SUSPEND" if t >= 100 else "NOTIFY"
                prompt_parts.append("  TRIGGERS ON " + str(t) + " PERCENT DO " + action)
            prompt_parts.append("  Assign to warehouse " + wh_name)
        prompt_parts.append("")

    # --- Tags ---
    if gov.get("tagging", True):
        prompt_parts.append("=== TAGS ===")
        first_db = resolve_name(project, envs[0], "DB", naming)
        prompt_parts.append("Create tags in " + first_db + "." + domains[0] + " schema:")
        tags = ["ENVIRONMENT", "PROJECT", "BUSINESS_UNIT", "DATA_DOMAIN", "SENSITIVITY"]
        if gov.get("cost_tags", True):
            tags.append("COST_CENTER")
        for tag in tags:
            prompt_parts.append("- Tag: " + project + "_" + tag)
        prompt_parts.append("")

    # --- Masking Policies ---
    if gov.get("masking", True):
        prompt_parts.append("=== MASKING POLICIES ===")
        patterns = gov.get("mask_patterns", "EMAIL,SSN,PHONE,CREDIT_CARD").split(",")
        first_db = resolve_name(project, envs[0], "DB", naming)
        prompt_parts.append("Create masking policies in " + first_db + "." + domains[0] + ":")
        for p in patterns:
            p = p.strip()
            if p:
                prompt_parts.append("- " + project + "_MASK_" + p + " masking policy for VARCHAR columns, returns '***MASKED***' for unauthorized roles")
        prompt_parts.append("Authorized roles: " + project + "_ADMIN, " + project + "_DATA_ENGINEER")
        prompt_parts.append("")

    # --- Row Access Policies ---
    if gov.get("row_access", False):
        prompt_parts.append("=== ROW ACCESS POLICIES ===")
        prompt_parts.append("Create a sample row access policy that filters by CURRENT_ROLE().")
        prompt_parts.append("")

    # --- Network Policy ---
    if gov.get("network_policy", False) and gov.get("allowed_ips", ""):
        prompt_parts.append("=== NETWORK POLICY ===")
        prompt_parts.append("Create network policy " + project + "_NETWORK_POLICY with ALLOWED_IP_LIST = ('" + gov["allowed_ips"].replace(",", "','") + "')")
        prompt_parts.append("")

    # --- Initial Tables ---
    valid_tables = [t for t in initial_tables if t.get("name") and t.get("columns", "").strip()]
    if valid_tables:
        prompt_parts.append("=== TABLES ===")
        prompt_parts.append("Create these initial tables in EVERY environment database, in the specified domain schema.")
        for t in valid_tables:
            for env in envs:
                db_name = resolve_name(project, env, "DB", naming)
                fqn = db_name + "." + t["domain"] + "." + t["name"]
                tt_kw = "TRANSIENT " if t.get("table_type") == "TRANSIENT" else ""
                prompt_parts.append("- CREATE " + tt_kw + "TABLE IF NOT EXISTS " + fqn + " (")
                for col_line in t["columns"].strip().split("\n"):
                    col_line = col_line.strip()
                    if col_line:
                        prompt_parts.append("    " + col_line + ",")
                prompt_parts.append("  )")
                if t.get("comment"):
                    prompt_parts.append("  COMMENT = '" + t["comment"].replace("'", "''") + "'")
        prompt_parts.append("")

    # --- File Formats ---
    valid_formats = [f for f in file_formats if f.get("name")]
    first_env = envs[0] if envs else "DEV"
    if valid_formats:
        prompt_parts.append("=== FILE FORMATS ===")
        prompt_parts.append("Create named file formats in the specified schema of the first environment database.")
        ff_db = resolve_name(project, first_env, "DB", naming)
        for f in valid_formats:
            f_schema = f.get("schema", "RAW" if "RAW" in domains else domains[0])
            fqn = ff_db + "." + f_schema + "." + f["name"]
            prompt_parts.append("- CREATE FILE FORMAT IF NOT EXISTS " + fqn)
            prompt_parts.append("  TYPE = '" + f["type"] + "'")
            opts = f.get("options", {})
            if f["type"] == "CSV":
                prompt_parts.append("  FIELD_DELIMITER = '" + opts.get("field_delimiter", ",") + "'")
                prompt_parts.append("  SKIP_HEADER = " + str(opts.get("skip_header", 1)))
                prompt_parts.append("  COMPRESSION = '" + opts.get("compression", "AUTO") + "'")
                null_if = opts.get("null_if", "")
                if null_if:
                    prompt_parts.append("  NULL_IF = ('" + "', '".join([n.strip() for n in null_if.split(",")]) + "')")
            elif f["type"] == "JSON":
                if opts.get("strip_outer_array"):
                    prompt_parts.append("  STRIP_OUTER_ARRAY = TRUE")
                prompt_parts.append("  COMPRESSION = '" + opts.get("compression", "AUTO") + "'")
            elif f["type"] == "PARQUET":
                prompt_parts.append("  COMPRESSION = '" + opts.get("compression", "AUTO") + "'")
        prompt_parts.append("")

    # --- Stages & Ingestion ---
    valid_stages = [s for s in stages if s.get("name")]
    if valid_stages or ingestion:
        prompt_parts.append("=== STAGES & INGESTION OBJECTS ===")
        for env in envs:
            db_name = resolve_name(project, env, "DB", naming)
            for s in valid_stages:
                s_schema = s.get("schema", "RAW" if "RAW" in domains else domains[0])
                fqn = db_name + "." + s_schema + "." + s["name"]
                prompt_parts.append("- CREATE STAGE IF NOT EXISTS " + fqn)
                if s.get("file_format"):
                    ff_fmt_db = resolve_name(project, first_env, "DB", naming)
                    ff_fmt_obj = next((f for f in valid_formats if f.get("name") == s["file_format"]), None)
                    ff_fmt_schema = ff_fmt_obj.get("schema", "RAW") if ff_fmt_obj else "RAW"
                    ff_ref = ff_fmt_db + "." + ff_fmt_schema + "." + s["file_format"]
                    prompt_parts.append("  FILE_FORMAT = " + ff_ref)
                if s.get("comment"):
                    prompt_parts.append("  COMMENT = '" + s["comment"].replace("'", "''") + "'")
            if not valid_stages:
                stg_fallback = "RAW" if "RAW" in domains else domains[0]
                if "Snowpipe" in ingestion or "Batch (COPY INTO)" in ingestion:
                    prompt_parts.append("- Create internal stage " + db_name + "." + stg_fallback + "." + project + "_" + env + "_STAGE")
            if "Streams & Tasks" in ingestion:
                stg_fallback = "RAW" if "RAW" in domains else domains[0]
                prompt_parts.append("- Add placeholder STREAM and TASK objects in " + db_name + "." + stg_fallback)
        prompt_parts.append("")

    # --- Final requirements for the LLM ---
    prompt_parts.append("=== EXECUTION ORDER ===")
    prompt_parts.append("Generate SQL in this EXACT order:")
    prompt_parts.append("1. USE ROLE ACCOUNTADMIN; -- for resource monitors & network policies")
    prompt_parts.append("2. USE ROLE SYSADMIN;     -- for databases, schemas, warehouses, tables, stages, file formats")
    prompt_parts.append("3. CREATE databases, then schemas inside each database")
    prompt_parts.append("4. CREATE tables in their respective schemas")
    prompt_parts.append("5. CREATE file formats, then stages (stages may reference file formats)")
    prompt_parts.append("6. CREATE warehouses")
    prompt_parts.append("7. USE ROLE SECURITYADMIN; -- for roles, grants, policies")
    prompt_parts.append("8. CREATE roles and GRANT role hierarchy")
    prompt_parts.append("9. GRANT privileges on databases/schemas/warehouses to roles")
    prompt_parts.append("10. GRANT ON FUTURE TABLES/VIEWS for auto-inheritance")
    prompt_parts.append("11. USE ROLE ACCOUNTADMIN; -- for resource monitors")
    prompt_parts.append("12. CREATE resource monitors and assign to warehouses")
    prompt_parts.append("13. USE ROLE SYSADMIN; -- for tags, masking, row access policies")
    prompt_parts.append("14. CREATE tags, masking policies, row access policies, network policies")
    prompt_parts.append("")
    prompt_parts.append("=== FINAL REQUIREMENTS ===")
    prompt_parts.append("- Add COMMENT on every object for documentation")
    prompt_parts.append("- Use IF NOT EXISTS on all CREATE statements")
    prompt_parts.append("- Switch USE ROLE before each section as specified in EXECUTION ORDER above")
    prompt_parts.append("- Output ONLY executable SQL. No markdown. No explanations. No code fences.")

    result = "\n".join(prompt_parts)
    _dbg(f"User prompt built: {len(result)} chars, {result.count(chr(10))} lines")
    return result


# ---------------------------------------------------------------------------
# SQL post-processing utilities
# ---------------------------------------------------------------------------

def clean_sql(raw):
    """Strip markdown fences and empty content from LLM output."""
    text = raw.strip()
    if text.startswith("```"):
        first_nl = text.find("\n")
        if first_nl != -1:
            text = text[first_nl + 1:]
    if text.endswith("```"):
        text = text[:-3]
    lines = text.split("\n")
    cleaned = [l for l in lines if not l.strip().startswith("```")]
    result = "\n".join(cleaned).strip()
    if not result or all(c in (' ', '\n', '\t', ';') for c in result):
        return ""
    return result


def parse_sql_statements(sql_text):
    """Split a multi-statement SQL string on semicolons, preserving statement integrity."""
    stmts = []
    current = []
    for line in sql_text.split("\n"):
        current.append(line)
        stripped = line.strip()
        if stripped.endswith(";"):
            stmt = "\n".join(current).strip()
            if stmt and stmt != ";":
                stmts.append(stmt)
            current = []
    if current:
        remainder = "\n".join(current).strip()
        if remainder and remainder != ";":
            stmts.append(remainder)
    return stmts


def get_stmt_summary(stmt):
    """Return the first 80 chars of a statement for display."""
    first = stmt.strip().split("\n")[0][:80]
    return first


def categorize_statement(stmt):
    """Classify a SQL statement into a human-readable category for the exec log."""
    upper = stmt.strip().upper()
    if upper.startswith("CREATE TRANSIENT DATABASE") or upper.startswith("CREATE DATABASE"): return "Database"
    if upper.startswith("CREATE TRANSIENT SCHEMA") or upper.startswith("CREATE SCHEMA"): return "Schema"
    if upper.startswith("CREATE TABLE") or upper.startswith("CREATE TRANSIENT TABLE"): return "Table"
    if upper.startswith("CREATE FILE FORMAT"): return "File Format"
    if upper.startswith("CREATE WAREHOUSE"): return "Warehouse"
    if upper.startswith("CREATE ROLE"): return "Role"
    if "GRANT" in upper[:20]: return "Grant"
    if upper.startswith("CREATE RESOURCE MONITOR"): return "Resource Monitor"
    if upper.startswith("CREATE TAG") or upper.startswith("ALTER TAG"): return "Tag"
    if "MASKING POLICY" in upper: return "Masking Policy"
    if "ROW ACCESS POLICY" in upper: return "Row Access Policy"
    if "NETWORK POLICY" in upper: return "Network Policy"
    if upper.startswith("CREATE STAGE"): return "Stage"
    if upper.startswith("CREATE PIPE"): return "Pipe"
    if upper.startswith("CREATE STREAM"): return "Stream"
    if upper.startswith("CREATE TASK"): return "Task"
    if upper.startswith("USE "): return "Context"
    return "Other"


# ---------------------------------------------------------------------------
# Deployment engine — executes SQL with retries, logging, and progress UI
# ---------------------------------------------------------------------------

def execute_with_retry(stmt, retries=2):
    """Execute a single SQL statement with up to *retries* retry attempts."""
    for attempt in range(retries + 1):
        try:
            session.sql(stmt).collect()
            return {"success": True}
        except Exception as e:
            _dbg(f"Statement failed (attempt {attempt+1}/{retries+1}): {str(e)[:120]}")
            if attempt == retries:
                return {"success": False, "error": str(e)}
            time.sleep(1)


def log_audit(skill, model, prompt, sql, reviewed, deployed, status):
    """Insert an audit record into the skill audit log table (best-effort)."""
    try:
        safe_prompt = prompt.replace("'", "''")[:2000]
        safe_sql = sql.replace("'", "''")[:5000]
        session.sql(
            "INSERT INTO SKILL_DB.SKILLS.SKILL_AUDIT_LOG "
            "(SKILL_NAME, MODEL_USED, USER_PROMPT, GENERATED_SQL, WAS_APPROVED, WAS_EXECUTED, EXECUTION_STATUS) "
            "VALUES ('" + skill + "', '" + model + "', '" + safe_prompt + "', '" + safe_sql + "', "
            + str(reviewed).upper() + ", " + str(deployed).upper() + ", '" + status + "')"
        ).collect()
    except Exception as exc:
        _dbg(f"Audit log insert failed: {exc}")
        pass


def execute_sql_scripts(sql_text, deployment_id):
    """Parse and execute all SQL statements with a live progress bar.

    Returns a result dict with status, counts, duration, errors, and log.
    """
    _dbg(f"Starting deployment {deployment_id}")
    stmts = parse_sql_statements(sql_text)
    total = len(stmts)
    _dbg(f"Parsed {total} statements")
    if total == 0:
        return {"status": "FAILED", "total": 0, "successful": 0, "failed": 0, "duration": 0, "errors": [], "log": []}
    pb = st.progress(0)
    stxt = st.empty()
    metrics_html = st.empty()
    logc = st.expander("Execution Log", expanded=True)
    ok, fail, errs, elog, t0 = 0, 0, [], [], time.time()
    for i, stmt in enumerate(stmts):
        sm = get_stmt_summary(stmt)
        cat = categorize_statement(stmt)
        stxt.info("Exec " + str(i + 1) + "/" + str(total) + ": " + sm)
        pb.progress((i + 1) / total)
        r = execute_with_retry(stmt)
        el = round(time.time() - t0, 1)
        if r["success"]:
            ok += 1
            elog.append({"index": i + 1, "status": "OK", "category": cat, "summary": sm, "elapsed": el})
            with logc:
                st.text("OK: " + sm)
        else:
            fail += 1
            err_msg = r.get("error", "")[:300]
            errs.append({"statement": sm, "error": err_msg, "category": cat})
            elog.append({"index": i + 1, "status": "FAIL", "category": cat, "summary": sm, "error": err_msg, "elapsed": el})
            with logc:
                st.text("FAIL: " + sm)
        remaining = total - i - 1
        metrics_html.markdown(
            '<div class="deploy-metrics">'
            '<div class="deploy-metric ok"><div class="value">' + str(ok) + '</div><div class="label">Success</div></div>'
            '<div class="deploy-metric fail"><div class="value">' + str(fail) + '</div><div class="label">Failed</div></div>'
            '<div class="deploy-metric"><div class="value">' + str(remaining) + '</div><div class="label">Remaining</div></div>'
            '<div class="deploy-metric time"><div class="value">' + str(el) + 's</div><div class="label">Elapsed</div></div>'
            '</div>', unsafe_allow_html=True)
    d = round(time.time() - t0, 1)
    pb.progress(1.0)
    stxt.empty()
    s = "SUCCESS" if fail == 0 else ("FAILED" if ok == 0 else "PARTIAL")
    st.session_state.exec_log = elog
    return {"status": s, "total": total, "successful": ok, "failed": fail, "duration": d, "errors": errs, "log": elog}


# ---------------------------------------------------------------------------
# Main application layout
# ---------------------------------------------------------------------------

skills = load_skills()
skill_map = {s["name"]: s for s in skills}
_dbg(f"Loaded {len(skills)} skill(s)")

with st.sidebar:
    st.markdown("### Day-0 Platform Setup")
    # st.caption("Skill-Powered SQL Generation")
    st.divider()
    sk = list(skill_map.keys())
    di = sk.index("DAY0-ORCHESTRATOR") if "DAY0-ORCHESTRATOR" in sk else 0
    selected_skill_name = st.selectbox("Active Skill", options=sk, index=di)
    selected_skill = skill_map[selected_skill_name]
    st.markdown('<span class="skill-badge">' + selected_skill_name + '</span>', unsafe_allow_html=True)
    st.caption(selected_skill["description"])
    st.divider()
    mi = MODELS.index(selected_skill["model"]) if selected_skill["model"] in MODELS else 0
    selected_model = st.selectbox("LLM Model", MODELS, index=mi)
    st.divider()
    with st.expander("View Skill Guardrails"):
        st.code(selected_skill["content"], language="markdown")
    st.divider()
    for sn, sl in {1: "Project Setup", 2: "Environment Config", 3: "Security & Governance", 4: "Review & Deploy"}.items():
        pfx = "-> " if st.session_state.step == sn else "   "
        if st.button(pfx + str(sn) + ". " + sl, key="nav_" + str(sn), use_container_width=True):
            st.session_state.step = sn
            safe_rerun()
    st.divider()
    render_best_practices(st.session_state.step)

    # --- Debug panel & config export ---
    st.divider()
    with st.expander("Debug & Config", expanded=False):
        if st.button("Export Config JSON", key="export_cfg", use_container_width=True):
            st.code(json.dumps(st.session_state.config, indent=2, default=str), language="json")
        debug_entries = st.session_state.get("_debug_log", [])
        if debug_entries:
            st.caption(f"{len(debug_entries)} debug entries")
            st.code("\n".join(debug_entries[-50:]), language="text")
        else:
            st.caption("No debug entries yet.")

render_progress()
st.markdown("---")

# ==========================================================================
# Step 1 — Project Setup
# ==========================================================================
if st.session_state.step == 1:
    _dbg("Rendering Step 1")
    st.markdown('<span class="step-indicator">Step 1 of 4</span>', unsafe_allow_html=True)
    st.header("Project Setup")
    st.caption("Define the foundational configuration for your Snowflake data platform.")
    templates = load_templates()
    if templates:
        tnames = ["-- Select --"] + list(templates.keys())
        sel_t = st.selectbox("Load template", tnames)
        if sel_t != "-- Select --":
            tc = templates[sel_t]["config"]
            st.session_state.config = dict(tc) if isinstance(tc, dict) else json.loads(str(tc))
    st.subheader("Identification")
    c1, c2 = st.columns(2)
    with c1:
        pn = st.text_input("Project Name *", value=st.session_state.config.get("project_name", ""),
                           placeholder="e.g., SALES_ANALYTICS", help=TOOLTIP["project_name"])
        bu = st.text_input("Business Unit", value=st.session_state.config.get("business_unit", ""),
                           placeholder="e.g., Finance, Marketing", help=TOOLTIP["business_unit"])
        owner = st.text_input("Project Owner", value=st.session_state.config.get("project_owner", ""),
                              placeholder="e.g., jane.doe@company.com",
                              help="Primary contact for this platform project. Used for tagging and alerting.")
    with c2:
        envs = st.multiselect("Environments *", ["DEV", "QA", "UAT", "STAGING", "PROD"],
                              default=st.session_state.config.get("environments", ["DEV", "PROD"]),
                              help=TOOLTIP["environments"])
        nm = st.selectbox("Naming Convention",
                          ["<PROJECT>_<ENV>_<OBJECT>", "<ENV>_<PROJECT>_<OBJECT>"],
                          help=TOOLTIP["naming_convention"])
        region = st.selectbox("Primary Region",
                              ["US East (N. Virginia)", "US West (Oregon)", "EU (Frankfurt)",
                               "EU (Ireland)", "AP (Sydney)", "AP (Tokyo)"],
                              help="Primary cloud region. Affects data residency and latency.")
    st.subheader("Architecture")
    doms = st.multiselect("Data Domains *",
                          ["RAW", "STAGING", "CLEANSED", "CURATED", "ANALYTICS", "DATA_SCIENCE", "SANDBOX", "ARCHIVE"],
                          default=st.session_state.config.get("data_domains", ["RAW", "STAGING", "ANALYTICS"]),
                          help=TOOLTIP["data_domains"])
    st.subheader("Storage Type")
    st.caption("Control storage costs and recoverability per environment and domain.")
    sc1, sc2 = st.columns(2)
    with sc1:
        db_storage_type = st.selectbox(
            "Database Storage Type",
            ["PERMANENT", "TRANSIENT"],
            index=["PERMANENT", "TRANSIENT"].index(
                st.session_state.config.get("db_storage_type", "PERMANENT")),
            help=TOOLTIP["db_storage_type"])
    with sc2:
        if db_storage_type == "TRANSIENT":
            st.warning("Transient databases: Max 1-day Time Travel, NO Fail-Safe.", icon="⚠️")
        else:
            st.info("Permanent databases: Full Time Travel (0-90 days) + 7-day Fail-Safe.", icon="ℹ️")
    schema_storage_overrides = {}
    if doms:
        st.markdown("**Per-Domain Schema Storage Override**")
        st.caption("Override individual schemas to a different storage type than the database default.")
        override_cols = st.columns(min(len(doms), 4))
        for didx, dom in enumerate(doms):
            with override_cols[didx % min(len(doms), 4)]:
                prev_overrides = st.session_state.config.get("schema_storage_overrides", {})
                opts = ["INHERIT", "PERMANENT", "TRANSIENT"]
                prev_val = prev_overrides.get(dom, "INHERIT")
                schema_storage_overrides[dom] = st.selectbox(
                    dom, opts,
                    index=opts.index(prev_val) if prev_val in opts else 0,
                    key="schema_st_" + dom,
                    help=TOOLTIP["schema_storage_type"])
    st.subheader("Data Ingestion")
    ing = st.multiselect("Ingestion Methods",
                         ["Batch (COPY INTO)", "Snowpipe", "Streams & Tasks", "External Tables",
                          "Data Sharing", "Snowflake Connector for Kafka", "Dynamic Tables"],
                         default=st.session_state.config.get("ingestion_types", ["Batch (COPY INTO)"]),
                         help=TOOLTIP["ingestion_types"])
    st.subheader("Data Retention")
    tt_max = 1 if db_storage_type == "TRANSIENT" else 90
    tt_default = st.session_state.config.get("time_travel_days", 1)
    if tt_default > tt_max:
        tt_default = tt_max
    c1, c2 = st.columns(2)
    with c1:
        tt_days = st.slider("Time Travel (days)", min_value=0, max_value=tt_max,
                            value=tt_default,
                            help=TOOLTIP["data_retention"])
    with c2:
        if db_storage_type == "TRANSIENT":
            st.warning("Transient: NO Fail-Safe. Time Travel limited to 0-1 day.", icon="⚠️")
        else:
            st.info("Fail-Safe: 7 days (automatic after Time Travel)", icon="ℹ️")
    st.subheader("Initial Tables")
    st.caption("Define seed tables to scaffold your data pipeline. Add tables per domain with column definitions.")
    existing_tables = st.session_state.config.get("initial_tables", [])
    if st.button("+ Add Table", key="add_table_btn"):
        st.session_state.table_counter += 1
        existing_tables.append({
            "name": "", "domain": doms[0] if doms else "RAW",
            "table_type": "PERMANENT", "columns": "", "comment": ""
        })
        st.session_state.config["initial_tables"] = existing_tables
    tables_to_remove = []
    for tidx, tbl in enumerate(existing_tables):
        with st.expander("Table " + str(tidx + 1) + ": " + (tbl.get("name") or "(unnamed)"), expanded=not tbl.get("name")):
            tc1, tc2, tc3 = st.columns([2, 1, 1])
            with tc1:
                tbl["name"] = st.text_input(
                    "Table Name", value=tbl.get("name", ""),
                    key="tbl_name_" + str(tidx),
                    placeholder="e.g., RAW_ORDERS, STG_CUSTOMERS",
                    help=TOOLTIP["initial_tables"]).upper().replace(" ", "_")
            with tc2:
                domain_opts = doms if doms else ["RAW"]
                tbl["domain"] = st.selectbox(
                    "Target Schema", domain_opts,
                    index=domain_opts.index(tbl.get("domain", domain_opts[0])) if tbl.get("domain", domain_opts[0]) in domain_opts else 0,
                    key="tbl_dom_" + str(tidx))
            with tc3:
                type_opts = ["PERMANENT", "TRANSIENT"]
                tbl["table_type"] = st.selectbox(
                    "Table Type", type_opts,
                    index=type_opts.index(tbl.get("table_type", "PERMANENT")) if tbl.get("table_type", "PERMANENT") in type_opts else 0,
                    key="tbl_type_" + str(tidx),
                    help=TOOLTIP["table_type"])
            tbl["columns"] = st.text_area(
                "Column Definitions (one per line: NAME DATATYPE)",
                value=tbl.get("columns", ""),
                key="tbl_cols_" + str(tidx),
                height=100,
                placeholder="ID NUMBER NOT NULL\nNAME VARCHAR(255)\nCREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()\nIS_ACTIVE BOOLEAN DEFAULT TRUE",
                help=TOOLTIP["table_columns"])
            tbl["comment"] = st.text_input(
                "Table Comment", value=tbl.get("comment", ""),
                key="tbl_cmt_" + str(tidx),
                placeholder="e.g., Raw order data from source system")
            if st.button("Remove", key="tbl_rm_" + str(tidx)):
                tables_to_remove.append(tidx)
    for ri in sorted(tables_to_remove, reverse=True):
        existing_tables.pop(ri)
    st.session_state.config["initial_tables"] = existing_tables
    if existing_tables:
        tbl_summary_parts = []
        for t in existing_tables:
            if t.get("name"):
                col_count = len([c for c in t.get("columns", "").strip().split("\n") if c.strip()])
                tbl_summary_parts.append(t["domain"] + "." + t["name"] + " (" + t["table_type"] + ", " + str(col_count) + " cols)")
        if tbl_summary_parts:
            st.caption("Defined: " + " | ".join(tbl_summary_parts))
    st.subheader("File Formats")
    st.caption("Define reusable named file formats for data loading. Attached to the first environment's RAW schema.")
    existing_formats = st.session_state.config.get("file_formats", [])
    if st.button("+ Add File Format", key="add_ff_btn"):
        existing_formats.append({
            "name": "", "type": "CSV",
            "options": {"field_delimiter": ",", "skip_header": 1, "compression": "AUTO",
                        "strip_outer_array": False, "null_if": ""}
        })
        st.session_state.config["file_formats"] = existing_formats
    ffs_to_remove = []
    for fidx, ff in enumerate(existing_formats):
        with st.expander("Format " + str(fidx + 1) + ": " + (ff.get("name") or "(unnamed)"), expanded=not ff.get("name")):
            fc1, fc2, fc3 = st.columns(3)
            with fc1:
                ff["name"] = st.text_input(
                    "Format Name", value=ff.get("name", ""),
                    key="ff_name_" + str(fidx),
                    placeholder="e.g., CSV_STANDARD, JSON_RAW",
                    help=TOOLTIP["file_formats"]).upper().replace(" ", "_")
            with fc2:
                fmt_types = ["CSV", "JSON", "PARQUET", "AVRO", "ORC"]
                ff["type"] = st.selectbox(
                    "Format Type", fmt_types,
                    index=fmt_types.index(ff.get("type", "CSV")),
                    key="ff_type_" + str(fidx))
            with fc3:
                ff_schema_opts = doms if doms else ["RAW"]
                ff_prev_schema = ff.get("schema", ff_schema_opts[0])
                ff["schema"] = st.selectbox(
                    "Target Schema", ff_schema_opts,
                    index=ff_schema_opts.index(ff_prev_schema) if ff_prev_schema in ff_schema_opts else 0,
                    key="ff_schema_" + str(fidx),
                    help="Schema where this file format will be created.")
            if ff["type"] == "CSV":
                oc1, oc2, oc3, oc4 = st.columns(4)
                with oc1:
                    ff["options"]["field_delimiter"] = st.text_input(
                        "Field Delimiter", value=ff["options"].get("field_delimiter", ","),
                        key="ff_delim_" + str(fidx))
                with oc2:
                    ff["options"]["skip_header"] = st.number_input(
                        "Skip Header Rows", min_value=0, max_value=10,
                        value=ff["options"].get("skip_header", 1),
                        key="ff_skip_" + str(fidx))
                with oc3:
                    ff["options"]["compression"] = st.selectbox(
                        "Compression", ["AUTO", "GZIP", "BZ2", "BROTLI", "ZSTD", "DEFLATE", "NONE"],
                        key="ff_comp_" + str(fidx))
                with oc4:
                    ff["options"]["null_if"] = st.text_input(
                        "NULL_IF values (comma-sep)", value=ff["options"].get("null_if", ""),
                        key="ff_null_" + str(fidx), placeholder="\\\\N, NULL, ''")
            elif ff["type"] == "JSON":
                jc1, jc2 = st.columns(2)
                with jc1:
                    ff["options"]["strip_outer_array"] = st.checkbox(
                        "Strip Outer Array", value=ff["options"].get("strip_outer_array", False),
                        key="ff_strip_" + str(fidx))
                with jc2:
                    ff["options"]["compression"] = st.selectbox(
                        "Compression", ["AUTO", "GZIP", "BZ2", "BROTLI", "ZSTD", "DEFLATE", "NONE"],
                        key="ff_jcomp_" + str(fidx))
            elif ff["type"] == "PARQUET":
                ff["options"]["compression"] = st.selectbox(
                    "Compression", ["AUTO", "SNAPPY", "LZO", "NONE"],
                    key="ff_pcomp_" + str(fidx))
            if st.button("Remove", key="ff_rm_" + str(fidx)):
                ffs_to_remove.append(fidx)
    for ri in sorted(ffs_to_remove, reverse=True):
        existing_formats.pop(ri)
    st.session_state.config["file_formats"] = existing_formats
    st.subheader("Stages")
    st.caption("Define named internal stages for data landing. Created in each environment's RAW schema (if RAW domain exists).")
    existing_stages = st.session_state.config.get("stages", [])
    if st.button("+ Add Stage", key="add_stage_btn"):
        existing_stages.append({"name": "", "comment": "", "file_format": ""})
        st.session_state.config["stages"] = existing_stages
    stgs_to_remove = []
    for sidx, stg in enumerate(existing_stages):
        with st.expander("Stage " + str(sidx + 1) + ": " + (stg.get("name") or "(unnamed)"), expanded=not stg.get("name")):
            sc1, sc2 = st.columns(2)
            with sc1:
                stg["name"] = st.text_input(
                    "Stage Name", value=stg.get("name", ""),
                    key="stg_name_" + str(sidx),
                    placeholder="e.g., LANDING_STAGE, RAW_INGEST",
                    help=TOOLTIP["stages"]).upper().replace(" ", "_")
            with sc2:
                stg_schema_opts = doms if doms else ["RAW"]
                stg_prev_schema = stg.get("schema", stg_schema_opts[0])
                stg["schema"] = st.selectbox(
                    "Target Schema", stg_schema_opts,
                    index=stg_schema_opts.index(stg_prev_schema) if stg_prev_schema in stg_schema_opts else 0,
                    key="stg_schema_" + str(sidx),
                    help="Schema where this stage will be created.")
            sc3, sc4 = st.columns(2)
            with sc3:
                ff_names = ["(none)"] + [f.get("name", "") for f in existing_formats if f.get("name")]
                prev_ff = stg.get("file_format", "")
                stg["file_format"] = st.selectbox(
                    "Default File Format", ff_names,
                    index=ff_names.index(prev_ff) if prev_ff in ff_names else 0,
                    key="stg_ff_" + str(sidx))
                if stg["file_format"] == "(none)":
                    stg["file_format"] = ""
            with sc4:
                stg["comment"] = st.text_input(
                    "Comment", value=stg.get("comment", ""),
                    key="stg_cmt_" + str(sidx), placeholder="e.g., Landing zone for batch loads")
            if st.button("Remove", key="stg_rm_" + str(sidx)):
                stgs_to_remove.append(sidx)
    for ri in sorted(stgs_to_remove, reverse=True):
        existing_stages.pop(ri)
    st.session_state.config["stages"] = existing_stages
    _, cn = st.columns(2)
    with cn:
        if st.button("Next: Environment Config ->", type="primary", use_container_width=True):
            if not pn or not envs:
                st.error("Project Name and at least one Environment are required.")
            elif not doms:
                st.error("Select at least one Data Domain.")
            else:
                # Validate table definitions before proceeding
                has_table_error = False
                named_tables = [t for t in existing_tables if t.get("name")]
                tbl_keys = [t["domain"] + "." + t["name"] for t in named_tables]
                if len(tbl_keys) != len(set(tbl_keys)):
                    st.error("Duplicate table name detected. Each table must be unique within its domain.")
                    has_table_error = True
                for t in named_tables:
                    if not t.get("columns", "").strip():
                        st.error(f"Table '{t['name']}' has no column definitions. Add columns or remove the table.")
                        has_table_error = True
                        break
                if not has_table_error:
                    _dbg(f"Step 1 complete: project={pn}, envs={envs}, domains={doms}, "
                         f"tables={len(named_tables)}, formats={len(existing_formats)}, stages={len(existing_stages)}")
                    st.session_state.config.update({
                        "project_name": pn.upper().replace(" ", "_"), "business_unit": bu,
                        "project_owner": owner, "environments": envs, "naming_convention": nm,
                        "region": region, "data_domains": doms, "ingestion_types": ing,
                        "time_travel_days": tt_days,
                        "db_storage_type": db_storage_type,
                        "schema_storage_overrides": schema_storage_overrides,
                        "initial_tables": existing_tables,
                        "file_formats": existing_formats,
                        "stages": existing_stages,
                    })
                    st.session_state.step = 2
                    safe_rerun()

# ==========================================================================
# Step 2 — Environment Configuration (Warehouses)
# ==========================================================================
elif st.session_state.step == 2:
    _dbg("Rendering Step 2")
    st.markdown('<span class="step-indicator">Step 2 of 4</span>', unsafe_allow_html=True)
    st.header("Environment Configuration")
    st.caption("Configure compute resources per environment. Right-size warehouses to balance cost and performance.")
    wc = st.session_state.config.get("warehouse_config", {})
    envs = st.session_state.config.get("environments", ["DEV", "PROD"])
    env_tabs = st.tabs(envs)
    sizes = ["XSMALL", "SMALL", "MEDIUM", "LARGE", "XLARGE", "2XLARGE"]
    credit_map = {"XSMALL": 1, "SMALL": 2, "MEDIUM": 4, "LARGE": 8, "XLARGE": 16, "2XLARGE": 32}
    for idx, env in enumerate(envs):
        with env_tabs[idx]:
            ex = wc.get(env, {})
            is_prod = env in ("PROD", "UAT", "STAGING")
            wh_display = resolve_name(st.session_state.config.get("project_name", "PROJECT"), env, "WH", st.session_state.config.get("naming_convention", "<PROJECT>_<ENV>_<OBJECT>"))
            st.markdown("**Warehouse: " + wh_display + "**")
            c1, c2 = st.columns(2)
            with c1:
                sz = st.selectbox("Warehouse Size", sizes,
                                  index=sizes.index(ex.get("size", "MEDIUM" if is_prod else "SMALL")),
                                  key="sz_" + env, help=TOOLTIP["warehouse_size"])
                asusp = st.number_input("Auto Suspend (seconds)", 60, 3600,
                                        ex.get("auto_suspend", 300 if is_prod else 120),
                                        key="as_" + env, help=TOOLTIP["auto_suspend"])
                sp = st.selectbox("Scaling Policy", ["STANDARD", "ECONOMY"],
                                  index=0 if is_prod else 1, key="sp_" + env, help=TOOLTIP["scaling_policy"])
            with c2:
                minc = st.number_input("Min Clusters", 1, 10, ex.get("min_clusters", 1),
                                       key="mn_" + env, help=TOOLTIP["min_clusters"])
                maxc = st.number_input("Max Clusters", 1, 10,
                                       ex.get("max_clusters", 3 if is_prod else 1),
                                       key="mx_" + env, help=TOOLTIP["max_clusters"])
                qt = st.number_input("Statement Timeout (seconds)", 60, 86400,
                                     ex.get("query_timeout", 3600 if is_prod else 300),
                                     key="qt_" + env, help=TOOLTIP["query_timeout"])
            est_credits = credit_map.get(sz, 2) * minc
            st.caption("Estimated base cost: ~" + str(est_credits) + " credits/hr (when active)")
            rm = st.number_input("Resource Monitor Credit Limit (monthly)", 10, 100000,
                                 ex.get("resource_monitor_credits", 1000 if is_prod else 100),
                                 key="rm_" + env, help=TOOLTIP["resource_monitor"])
            wc[env] = {"size": sz, "auto_suspend": asusp, "min_clusters": minc, "max_clusters": maxc,
                       "scaling_policy": sp, "query_timeout": qt, "resource_monitor_credits": rm}
            # Warn on cluster misconfiguration
            if minc > maxc:
                st.warning(f"Min clusters ({minc}) > Max clusters ({maxc}) for {env}. Max will be used as floor.", icon="⚠️")
    st.session_state.config["warehouse_config"] = wc
    st.subheader("Additional Warehouses")
    add_etl_wh = st.checkbox("Create separate ETL warehouse per environment",
                             value=st.session_state.config.get("separate_etl_wh", False),
                             help="Isolate ETL/batch workloads from interactive queries. Recommended for PROD.")
    st.session_state.config["separate_etl_wh"] = add_etl_wh
    cp, cn = st.columns(2)
    with cp:
        if st.button("<- Back", use_container_width=True):
            st.session_state.step = 1
            safe_rerun()
    with cn:
        if st.button("Next: Security & Governance ->", type="primary", use_container_width=True):
            st.session_state.step = 3
            safe_rerun()

# ==========================================================================
# Step 3 — Security & Governance
# ==========================================================================
elif st.session_state.step == 3:
    _dbg("Rendering Step 3")
    st.markdown('<span class="step-indicator">Step 3 of 4</span>', unsafe_allow_html=True)
    st.header("Security & Governance")
    st.caption("Define access controls, data protection policies, and compliance settings for your platform.")
    st.subheader("Role Hierarchy")
    roles = st.multiselect("Functional Roles",
                           ["ADMIN", "DEVELOPER", "DATA_ENGINEER", "ANALYST", "DATA_SCIENTIST",
                            "READER", "WRITER", "SERVICE_ACCOUNT"],
                           default=st.session_state.config.get("roles", ["ADMIN", "DEVELOPER", "ANALYST", "READER"]),
                           help=TOOLTIP["roles"])
    st.subheader("Data Protection")
    c1, c2 = st.columns(2)
    gov = st.session_state.config.get("governance", {})
    with c1:
        em = st.toggle("Dynamic Data Masking", value=gov.get("masking", True), help=TOOLTIP["masking"])
        if em:
            mask_cols = st.text_input("Sensitive column patterns (comma-separated)",
                                      value=gov.get("mask_patterns", "EMAIL,SSN,PHONE,CREDIT_CARD"),
                                      help="Column name patterns to auto-apply masking. Matched case-insensitively.")
        else:
            mask_cols = ""
        er = st.toggle("Row Access Policies", value=gov.get("row_access", False), help=TOOLTIP["row_access"])
    with c2:
        ec = st.toggle("Projection Policies", value=gov.get("column_access", False), help=TOOLTIP["column_access"])
        enp = st.toggle("Network Policy", value=gov.get("network_policy", False), help=TOOLTIP["network_policy"])
        if enp:
            allowed_ips = st.text_input("Allowed IP ranges (comma-separated)",
                                        value=gov.get("allowed_ips", ""),
                                        placeholder="e.g., 10.0.0.0/8, 192.168.1.0/24")
        else:
            allowed_ips = ""
    st.subheader("Classification & Tracking")
    c1, c2 = st.columns(2)
    with c1:
        et = st.toggle("Object Tagging", value=gov.get("tagging", True), help=TOOLTIP["tagging"])
        ecl = st.toggle("Data Classification", value=gov.get("classification", True), help=TOOLTIP["classification"])
    with c2:
        eah = st.toggle("Access History Tracking", value=gov.get("access_history", True), help=TOOLTIP["access_history"])
    st.subheader("Cost Management")
    c1, c2 = st.columns(2)
    with c1:
        ect = st.toggle("Cost Center Tags", value=gov.get("cost_tags", True), help=TOOLTIP["cost_tags"])
        erm = st.toggle("Resource Monitors", value=gov.get("resource_monitors", True), help=TOOLTIP["resource_monitors"])
    with c2:
        cq = st.number_input("Monthly Credit Quota (all environments)", 10, 100000,
                             st.session_state.config.get("cost_management", {}).get("credit_quota", 500),
                             help=TOOLTIP["credit_quota"])
        if erm:
            alert_thresholds = st.multiselect("Alert Thresholds (%)", [50, 75, 80, 90, 95, 100],
                                              default=[75, 90, 100],
                                              help="Percentage of credit quota that triggers notifications.")
        else:
            alert_thresholds = []
    st.session_state.config["roles"] = roles
    st.session_state.config["governance"] = {
        "masking": em, "mask_patterns": mask_cols, "row_access": er, "column_access": ec,
        "network_policy": enp, "allowed_ips": allowed_ips, "tagging": et, "classification": ecl,
        "access_history": eah, "cost_tags": ect, "resource_monitors": erm, "alert_thresholds": alert_thresholds,
    }
    st.session_state.config["cost_management"] = {"credit_quota": cq}
    cp, cn = st.columns(2)
    with cp:
        if st.button("<- Back", use_container_width=True, key="s3b"):
            st.session_state.step = 2
            safe_rerun()
    with cn:
        if st.button("Next: Review & Deploy ->", type="primary", use_container_width=True, key="s3n"):
            st.session_state.step = 4
            safe_rerun()

# ==========================================================================
# Step 4 — Review & Deploy
# ==========================================================================
elif st.session_state.step == 4:
    _dbg("Rendering Step 4")
    st.markdown('<span class="step-indicator">Step 4 of 4</span>', unsafe_allow_html=True)
    s4h1, s4h2 = st.columns([4, 1])
    with s4h1:
        st.header("Review & Deploy")
    with s4h2:
        st.markdown('<div class="reset-btn-wrap">', unsafe_allow_html=True)
        if st.button("Reset & Start Over", key="reset_top", use_container_width=True):
            st.session_state.config = {}
            st.session_state.generated_sql = None
            st.session_state.deployment_complete = False
            st.session_state.deployment_result = None
            st.session_state.exec_log = []
            st.session_state.review_confirmed = False
            st.session_state.validation_sql = None
            st.session_state.validation_results = []
            st.session_state.table_counter = 0
            st.session_state.step = 1
            _dbg("Full reset triggered from Step 4 header")
            safe_rerun()
        st.markdown('</div>', unsafe_allow_html=True)
    st.caption("Review your configuration, generate SQL, and deploy to Snowflake.")
    with st.expander("Configuration Summary", expanded=True):
        c1, c2, c3, c4 = st.columns(4)
        with c1:
            envs = st.session_state.config.get("environments", [])
            st.markdown('<div class="summary-card"><h4>Project</h4>'
                        '<p><strong>' + str(st.session_state.config.get("project_name", "N/A")) + '</strong></p>'
                        '<p>Owner: ' + str(st.session_state.config.get("project_owner", "N/A")) + '</p>'
                        '<p>Unit: ' + str(st.session_state.config.get("business_unit", "N/A")) + '</p>'
                        '<p>Envs: ' + ", ".join(envs) + '</p></div>', unsafe_allow_html=True)
        with c2:
            doms = st.session_state.config.get("data_domains", [])
            ings = st.session_state.config.get("ingestion_types", [])
            db_st = st.session_state.config.get("db_storage_type", "PERMANENT")
            s_overrides = st.session_state.config.get("schema_storage_overrides", {})
            overridden = [d + "=" + t for d, t in s_overrides.items() if t != "INHERIT"]
            storage_line = "DB: " + db_st
            if overridden:
                storage_line += "<br>Overrides: " + ", ".join(overridden)
            st.markdown('<div class="summary-card"><h4>Architecture</h4>'
                        '<p>Domains: ' + ", ".join(doms) + '</p>'
                        '<p>Ingestion: ' + ", ".join(ings) + '</p>'
                        '<p>Storage: ' + storage_line + '</p>'
                        '<p>Time Travel: ' + str(st.session_state.config.get("time_travel_days", 1)) + 'd</p>'
                        '<p>Tables: ' + str(len([t for t in st.session_state.config.get("initial_tables", []) if t.get("name")])) + '</p>'
                        '<p>File Formats: ' + str(len([f for f in st.session_state.config.get("file_formats", []) if f.get("name")])) + '</p>'
                        '<p>Stages: ' + str(len([s for s in st.session_state.config.get("stages", []) if s.get("name")])) + '</p></div>',
                        unsafe_allow_html=True)
        with c3:
            wc = st.session_state.config.get("warehouse_config", {})
            wh_summary = "<br>".join([e + ": " + c.get("size", "?") for e, c in wc.items()])
            st.markdown('<div class="summary-card"><h4>Compute</h4><p>' + wh_summary + '</p></div>',
                        unsafe_allow_html=True)
        with c4:
            rls = st.session_state.config.get("roles", [])
            gov = st.session_state.config.get("governance", {})
            features = [k for k, v in gov.items() if v is True]
            st.markdown('<div class="summary-card"><h4>Security</h4>'
                        '<p>Roles: ' + ", ".join(rls) + '</p>'
                        '<p>Policies: ' + ", ".join(features[:4]) + '</p></div>', unsafe_allow_html=True)
    st.markdown('<span class="skill-badge">Skill: ' + selected_skill_name + '</span> &nbsp; Model: **' + selected_model + '**', unsafe_allow_html=True)
    st.markdown("")
    tab_g, tab_s, tab_d, tab_log = st.tabs(["1. Generate SQL", "2. Review & Approve", "3. Deploy", "4. Summary & Validate"])
    with tab_g:
        st.subheader("Generate Platform SQL")
        st.caption("The selected skill and LLM will produce all DDL statements based on your configuration.")
        if st.button("Generate SQL with " + selected_skill_name, type="primary", use_container_width=True):
            if not st.session_state.config.get("project_name"):
                st.error("Go back to Step 1 and configure your project first.")
            else:
                up = build_user_prompt(st.session_state.config)
                with st.spinner("Generating with " + selected_skill_name + " skill using " + selected_model + "..."):
                    try:
                        raw, usage = call_cortex_complete(selected_model, selected_skill["content"], up)
                        st.session_state.generated_sql = clean_sql(raw)
                        log_audit(selected_skill_name, selected_model, up[:2000],
                                  st.session_state.generated_sql[:5000], False, False, "GENERATED")
                        st.session_state.validation_sql = build_validation_sql(st.session_state.config)
                        st.session_state.review_confirmed = False
                        st.success("SQL generated successfully! Proceed to the Review Script tab.")
                    except Exception as e:
                        st.error("Generation failed: " + str(e))
        if st.session_state.generated_sql:
            st.info("SQL is ready. Switch to the **Review Script** tab to inspect before deploying.")
    with tab_s:
        if st.session_state.generated_sql:
            stmts = parse_sql_statements(st.session_state.generated_sql)
            categories = {}
            for s in stmts:
                cat = categorize_statement(s)
                categories.setdefault(cat, []).append(s)
            st.subheader("Generated Script: " + str(len(stmts)) + " statements")
            st.markdown("**What will be created:**")
            summary_cols = st.columns(min(len(categories), 4))
            for i, (cat, items) in enumerate(categories.items()):
                with summary_cols[i % len(summary_cols)]:
                    st.metric(cat, len(items))
            view_mode = st.radio("View mode", ["By Category", "Full Script", "By Statement"], horizontal=True)
            if view_mode == "By Category":
                for cat, items in categories.items():
                    with st.expander(cat + " (" + str(len(items)) + " statements)", expanded=False):
                        for j, s in enumerate(items):
                            st.code(s, language="sql")
            elif view_mode == "Full Script":
                st.code(st.session_state.generated_sql, language="sql")
            else:
                for i, s in enumerate(stmts):
                    cat = categorize_statement(s)
                    with st.expander("[" + cat + "] Stmt " + str(i + 1) + ": " + get_stmt_summary(s)):
                        st.code(s, language="sql")
            if st.session_state.validation_sql:
                with st.expander("Validation SQL (will run in Summary tab after deploy)", expanded=False):
                    st.code(st.session_state.validation_sql, language="sql")
            st.divider()
            if st.session_state.review_confirmed:
                rc1, rc2 = st.columns([3, 1])
                with rc1:
                    st.success("Review confirmed. Proceed to the Deploy tab.")
                with rc2:
                    st.markdown('<div class="reset-btn-wrap">', unsafe_allow_html=True)
                    if st.button("Reset & Restart", key="reset_review", use_container_width=True):
                        st.session_state.generated_sql = None
                        st.session_state.deployment_complete = False
                        st.session_state.deployment_result = None
                        st.session_state.exec_log = []
                        st.session_state.review_confirmed = False
                        st.session_state.validation_sql = None
                        st.session_state.validation_results = []
                        st.session_state.step = 1
                        _dbg("Reset & Restart triggered from Review tab")
                        safe_rerun()
                    st.markdown('</div>', unsafe_allow_html=True)
            else:
                st.warning("You must confirm your review before deploying.")
                rc1, rc2 = st.columns([3, 1])
                with rc1:
                    if st.button("I have reviewed and approve this SQL", type="primary", use_container_width=True, key="confirm_review"):
                        st.session_state.review_confirmed = True
                        safe_rerun()
                with rc2:
                    st.markdown('<div class="reset-btn-wrap">', unsafe_allow_html=True)
                    if st.button("Reset & Restart", key="reset_prereview", use_container_width=True):
                        st.session_state.generated_sql = None
                        st.session_state.review_confirmed = False
                        st.session_state.step = 1
                        _dbg("Reset & Restart triggered from pre-review")
                        safe_rerun()
                    st.markdown('</div>', unsafe_allow_html=True)
        else:
            st.info("Generate SQL in the previous tab first.")
    with tab_d:
        if st.session_state.generated_sql:
            if not st.session_state.review_confirmed:
                st.warning("You must confirm your review in the **Review & Approve** tab before deploying.")
            elif not st.session_state.get("deployment_complete"):
                stmts = parse_sql_statements(st.session_state.generated_sql)
                categories = {}
                for s in stmts:
                    cat = categorize_statement(s)
                    categories.setdefault(cat, []).append(s)
                st.subheader("Deployment Plan")
                st.markdown("**" + str(len(stmts)) + " statements** will be executed in order:")
                for cat, items in categories.items():
                    st.markdown("- **" + cat + "**: " + str(len(items)) + " statement(s)")
                st.info("Review approved. Ready to deploy.", icon="✅")
                bc, bd = st.columns(2)
                with bc:
                    if st.button("Cancel", use_container_width=True):
                        st.session_state.generated_sql = None
                        st.session_state.review_confirmed = False
                        safe_rerun()
                with bd:
                    if st.button("Deploy to Snowflake", type="primary", use_container_width=True):
                        did = "DEP_" + datetime.now().strftime("%Y%m%d_%H%M%S")
                        r = execute_sql_scripts(st.session_state.generated_sql, did)
                        st.session_state.deployment_result = r
                        st.session_state.deployment_complete = True
                        log_audit(selected_skill_name, selected_model, "", "",
                                  True, True, r["status"])
                        if r["status"] == "SUCCESS":
                            st.markdown('<div class="success-box"><h3>Deployment Successful</h3><p>'
                                        + str(r["successful"]) + '/' + str(r["total"])
                                        + ' statements executed in ' + str(r["duration"]) + 's</p></div>',
                                        unsafe_allow_html=True)
                        elif r["status"] == "PARTIAL":
                            st.warning("Partial deployment: " + str(r["successful"]) + " succeeded, "
                                       + str(r["failed"]) + " failed")
                        else:
                            st.error("Deployment failed. Check the Summary & Validate tab for details.")
                        if r.get("errors"):
                            with st.expander("Errors (" + str(len(r["errors"])) + ")", expanded=False):
                                for err in r["errors"]:
                                    st.error("[" + err.get("category", "") + "] " + err.get("statement", "")
                                             + "\n\n" + err.get("error", "")[:300])
                        st.info("See the **Summary & Validate** tab to verify created objects.")
            else:
                r = st.session_state.deployment_result
                if r:
                    if r["status"] == "SUCCESS":
                        st.markdown('<div class="success-box"><h3>Deployment Complete</h3><p>'
                                    + str(r["successful"]) + '/' + str(r["total"])
                                    + ' in ' + str(r["duration"]) + 's</p></div>', unsafe_allow_html=True)
                    else:
                        st.warning("Status: " + r["status"] + " (" + str(r["successful"]) + "/" + str(r["total"]) + ")")
                st.markdown('<div class="reset-btn-wrap">', unsafe_allow_html=True)
                if st.button("Start New Deployment", use_container_width=True):
                    st.session_state.generated_sql = None
                    st.session_state.deployment_complete = False
                    st.session_state.deployment_result = None
                    st.session_state.exec_log = []
                    st.session_state.review_confirmed = False
                    st.session_state.validation_sql = None
                    st.session_state.validation_results = []
                    st.session_state.step = 1
                    safe_rerun()
                st.markdown('</div>', unsafe_allow_html=True)
        else:
            st.info("Generate SQL first, then review and approve before deploying.")
    with tab_log:
        st.subheader("Summary & Validate")
        r = st.session_state.get("deployment_result")
        log = st.session_state.get("exec_log", [])
        if r and log:
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("Total Statements", r["total"])
            c2.metric("Successful", r["successful"])
            c3.metric("Failed", r["failed"])
            c4.metric("Duration", str(r["duration"]) + "s")
            st.markdown("**Breakdown by Category**")
            cat_stats = {}
            for entry in log:
                cat = entry.get("category", "Other")
                cat_stats.setdefault(cat, {"ok": 0, "fail": 0})
                if entry["status"] == "OK":
                    cat_stats[cat]["ok"] += 1
                else:
                    cat_stats[cat]["fail"] += 1
            cat_cols = st.columns(min(len(cat_stats), 4))
            for i, (cat, stats) in enumerate(cat_stats.items()):
                with cat_cols[i % len(cat_cols)]:
                    total_cat = stats["ok"] + stats["fail"]
                    pct = round(stats["ok"] / total_cat * 100) if total_cat else 0
                    st.metric(cat, str(stats["ok"]) + "/" + str(total_cat), delta=str(pct) + "% success")
            st.divider()
            st.subheader("Validate Created Objects")
            st.caption("Run validation queries to confirm all objects were created successfully in Snowflake.")
            if st.session_state.validation_sql:
                with st.expander("Validation SQL", expanded=False):
                    st.code(st.session_state.validation_sql, language="sql")
                if st.button("Run Validation", type="primary", use_container_width=True, key="run_validation"):
                    with st.spinner("Validating created objects..."):
                        vr = run_validation(st.session_state.validation_sql)
                        st.session_state.validation_results = vr
                vr = st.session_state.get("validation_results", [])
                if vr:
                    found = sum(1 for v in vr if v["status"] == "FOUND")
                    missing = sum(1 for v in vr if v["status"] == "MISSING")
                    errors = sum(1 for v in vr if v["status"] == "ERROR")
                    vc1, vc2, vc3 = st.columns(3)
                    vc1.metric("Found", found)
                    vc2.metric("Missing", missing)
                    vc3.metric("Errors", errors)
                    for v in vr:
                        if v["status"] == "FOUND":
                            st.markdown('<div class="exec-step exec-ok">&#10003; ' + v["object"] + ' &mdash; ' + v["detail"] + '</div>', unsafe_allow_html=True)
                        elif v["status"] == "MISSING":
                            st.markdown('<div class="exec-step exec-fail">&#10007; ' + v["object"] + ' &mdash; MISSING</div>', unsafe_allow_html=True)
                        else:
                            st.markdown('<div class="exec-step exec-fail">&#9888; ' + v["object"] + ' &mdash; ' + v["detail"] + '</div>', unsafe_allow_html=True)
            else:
                st.info("No validation SQL available. Generate SQL first.")
            st.divider()
            st.markdown("**Detailed Execution Log**")
            with st.expander("Execution Log", expanded=False):
                for entry in log:
                    cls = "exec-ok" if entry["status"] == "OK" else "exec-fail"
                    icon = "&#10003;" if entry["status"] == "OK" else "&#10007;"
                    err_text = (" | Error: " + entry.get("error", "")[:120]) if entry.get("error") else ""
                    st.markdown(
                        '<div class="exec-step ' + cls + '">' + icon + ' [' + entry.get("category", "")
                        + '] #' + str(entry["index"]) + ' &mdash; ' + entry["summary"] + err_text
                        + ' <span style="float:right;opacity:0.6">' + str(entry.get("elapsed", "")) + 's</span></div>',
                        unsafe_allow_html=True
                    )
            if st.button("Copy Execution Report"):
                report_lines = ["Deployment Report -- " + datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
                report_lines.append("Status: " + r["status"] + " | " + str(r["successful"]) + "/"
                                    + str(r["total"]) + " | " + str(r["duration"]) + "s\n")
                for entry in log:
                    status_icon = "OK" if entry["status"] == "OK" else "FAIL"
                    report_lines.append("[" + status_icon + "] [" + entry.get("category", "") + "] " + entry["summary"])
                vr = st.session_state.get("validation_results", [])
                if vr:
                    report_lines.append("\nValidation Results:")
                    for v in vr:
                        report_lines.append("[" + v["status"] + "] " + v["object"] + " -- " + v["detail"])
                st.code("\n".join(report_lines), language="text")
        elif r and not log:
            st.success("Deployment " + r["status"] + ": " + str(r["successful"]) + "/" + str(r["total"])
                       + " in " + str(r["duration"]) + "s")
        else:
            st.info("No deployment has been executed yet. Complete Steps 1-3, generate SQL, and deploy to see results here.")